language: php

matrix:
    include:
        - php: 5.6
          env: TEST_CONFIG="phpunit.xml"
        - php: 7.0
          env: TEST_CONFIG="phpunit.xml"
        - php: 7.2
          env: TEST_CONFIG="phpunit.xml" CHECK_CS=true
        - php: 7.0
          env: TEST_CONFIG="phpunit-integration-legacy.xml"
        - php: 5.6
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="4.10.4" CORES_SETUP="single" SOLR_CORES="collection1" SOLR_CONFIG="vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/schema.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/custom-fields-types.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/language-fieldtypes.xml"
        - php: 7.1
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="6.6.0" CORES_SETUP="shared" SOLR_CONFIG="vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/schema.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/custom-fields-types.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/language-fieldtypes.xml"

# test only master (+ Pull requests)
branches:
    only:
        - master

before_script:
    # Disable memory_limit for composer
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - mkdir -p ~/.composer
    - cp bin/.travis/composer-auth.json ~/.composer/auth.json
    - composer install --no-progress --no-interaction --prefer-dist
    - if [ "$SOLR_VERSION" != "" ] ; then ./vendor/ezsystems/ezplatform-solr-search-engine/bin/.travis/init_solr.sh ; fi

script:
    - php vendor/bin/phpunit --bootstrap tests/bootstrap.php -c $TEST_CONFIG
    - if [ "$CHECK_CS" == "true" ]; then phpenv config-rm xdebug.ini && ./vendor/bin/php-cs-fixer fix -v --dry-run --diff --show-progress=estimating; fi

notifications:
    email: false
