dist: trusty
language: php

services:
  - mysql
  - postgresql

# Mysql isn't installed on trusty (only client is), so we need to specifically install it
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: 5.6
          env: TEST_CONFIG="phpunit.xml"
        - php: 7.0
          env: TEST_CONFIG="phpunit.xml"
        - php: 7.2
          env: TEST_CONFIG="phpunit.xml" CHECK_CS=true
        - php: 7.0
          env: TEST_CONFIG="phpunit-integration-legacy.xml"
        - php: 5.6
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="4.10.4" CORES_SETUP="single" SOLR_CORES="collection1" SOLR_CONFIG="vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/schema.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/custom-fields-types.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/language-fieldtypes.xml"
        - php: 7.1
          env: TEST_CONFIG="phpunit-integration-legacy-solr.xml" SOLR_VERSION="6.6.0" CORES_SETUP="shared" SOLR_CONFIG="vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/schema.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/custom-fields-types.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/language-fieldtypes.xml"
        - php: 7.1
          env: TEST_CONFIG="phpunit-integration-legacy-empty-db.xml" DB="postgresql" DATABASE="pgsql://postgres@localhost/testdb"
        - php: 7.1
          env: TEST_CONFIG="phpunit-integration-legacy-empty-db.xml" DB="mysql" DATABASE="mysql://root@localhost/testdb"
        - php: 7.0
          env: TEST_CONFIG="phpunit.xml" COMPOSER_REQUIRE="ezsystems/ezpublish-kernel:^6.13.6@dev"

# test only master (+ Pull requests)
branches:
    only:
        - master
        - /^\d.\d+$/

# setup requirements for running db tests
before_install:
    - ./bin/.travis/prepare_unittest.sh

before_script:
    # Disable memory_limit for composer
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - travis_retry composer install --no-progress --no-interaction --prefer-dist
    - if [ "$SOLR_VERSION" != "" ] ; then ./vendor/ezsystems/ezplatform-solr-search-engine/bin/.travis/init_solr.sh ; fi

script:
    - php vendor/bin/phpunit -c $TEST_CONFIG
    - if [ "$CHECK_CS" == "true" ]; then ./vendor/bin/php-cs-fixer fix -v --dry-run --diff --show-progress=estimating; fi

notifications:
    email: false

# reduce depth (history) of git checkout
git:
    depth: 30
